name: Build Docker image and deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: .

      - uses: feavy/deploy@main
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          GITHUB_USERNAME: feavy
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DOCKERFILE_PATH: .
          DOCKER_IMAGE: feavy-nginx:latest
          DEPLOYMENT: deployment.yml

      - name: Restart deployment
        run: kubectl rollout restart deployment feavy-nginx
